package co.com.bancolombia.certificacion.svp.utilities.enums;

public enum TituloSubMenu {

    PROD_DEPOSIT_ACC_CONSULT_ACCOUNTS("link_prod_cuenta"),
    PROD_CTAS_DEPOSITO_VER_DETALLE_DE_TRANSACCIONES("link_prod_detail_transfer"),
    PROD_TDC_CONSULTAR_TARJETAS("link_prod_ctc"),
    PROD_TDC_PAGAR_TARJETAS("link_prod_pay_ownCard"),
    PROD_TDC_CAMBIAR_CUOTAS("link_prod_ccc"),
    PROD_CC_ADVANCES("link_prod_avtc"),
    PROD_CC_ACTIVATE_CARD("link_prod_activetc"),
    PROD_TDC_SOLICITAR_E_CARD("link_prod_aec"),
    PROD_CRED_CONSULTAR_CREDITOS("link_prod_ccr"),
    PROD_CRED_PAGAR_CREDITOS("link_prod_pay_cred"),
    PROD_CRED_DESEMBOLSAR_CREDIAGIL("link_prod_dca"),
    PROD_FID_CONSULTAR_FONDOS("link_prod_cfi"),
    PROD_FID_ABRIR_UN_FONDO("link_prod_afi"),
    PROD_FID_ADMINISTRAR_FONDOS("link_prod_adfi"),
    PROD_INV_CONSULT_INVESTMENT("link_prod_civ"),
    PROD_INV_OPEN_VIRTUAL_INVESTMENT("link_prod_aiv"),
    PROD_ADMIN_PROD_INSCRIBIR_CUENTAS("link_prod_aic"),
    PROD_ADMIN_PROD_PRODUCTOS_PROPIOS("link_prod_app"),
    PROD_ADMIN_PROD_PRODUCTOS_DE_TERCEROS("link_prod_apt"),
    PROD_E_PREPAGO_SOLICITAR("link_prod_sep"),
    PROD_E_PREPAGO_CONSULTAR("link_prod_conep"),
    PROD_E_PREPAGO_VER_MOVIMIENTOS("link_prod_mep"),
    PROD_E_PREPAGO_CARGAR("link_prod_cep"),
    PROD_E_PREPAGO_DESCARGAR("link_prod_dep"),
    PROD_E_PREPAGO_ACTIVAR("link_prod_aep"),
    PROD_E_PREPAGO_INACTIVAR("link_prod_iep"),
    PROD_BOLSILLOS_CREAR_BOLSILLOS("link_prod_pocket_create"),
    PROD_BOLSILLOS_CONSULTAR_BOLSILLOS("link_prod_pocket_consult"),
    PROD_BOLSILLOS_TRASNFERENCIA_BOLSILLOS("link_prod_pocket_transfer"),
    TRANS_A_CTAS_BANCO_TRANSFERIR("link_transf_aBancolombia"),
    TRANS_B_BANK_ACC_REGISTER_ACCOUNTS("link_transf_abcenrollaccts"),
    TRANS_A_CTAS_BANCO_VER_HISTORICO("link_transf_abchis"),
    TRANS_A_OTROS_BANCOS_TRANSFERIR("link_transf_aOthers"),
    TRANS_B_OTHERS_BANKS_REGISTER_ACCOUNTS("link_transf_abcenrollaccts"),
    TRANS_A_OTROS_BANCOS_VER_HISTORICO("link_transf_reaob"),
    TRANS_INTERNACIONALES_RECIBIR("link_transf_irecep"),
    TRANS_INTERNACIONALES_ENVIAR("link_transf_isend"),
    TRANS_INTERNACIONALES_INSCRIBIR_CUENTAS("link_transf_iaccregis"),
    TRANS_A_FONDOS_DE_INVERSION_TRANSFERIR("link_transf_aFondos"),
    TRANS_A_FONDOS_DE_INVERSION_INSCRIBIR_FONDOS("link_transf_fienroll"),
    TRANS_A_FONDOS_DE_INVERSION_VER_HISTORICO("link_transf_fihis"),
    TRANS_PROG_TRANSFERENCIAS_A_CUENTAS_DE_AHORRO_Y_CORRIENTE("link_transf_cacc"),
    TRANS_PROG_TRANSFERENCIAS_A_FONDOS_DE_INVERSION("link_transf_fi"),
    TRANS_PROG_TRANSFERENCIAS_VER_TRANSFERENCIAS_PROGRAMADAS("link_transf_progTrans"),
    PAGOS_TDC_PAGAR_TARJETA_PROPIA("link_payments_ownCard"),
    PAGOS_TDC_PAGAR_TARJETA_NO_PROPIA("link_payments_otherCard"),
    PAGOS_FACTURAS_PAGAR_FACTURAS("link_payments_repf"),
    PAGOS_FACTURAS_INSCRIBIR_FACTURAS("link_payments_insf"),
    PAGOS_FACTURAS_VER_HISTORICO("link_payments_hisf"),
    PAGOS_CRED_PAGAR_CREDITOS("link_payments_cred"),
    SEGUR_OPC_DE_CLAVE_CLAVE_DINAMICA("link_seguridad_ssecc"),
    SEGUR_BLOQUEOS_BLOQUEAR_TARJETAS("link_seguridad_bts"),
    SEGUR_BLOQUEOS_BLOQUEAR_CLAVE("link_seguridad_bcs"),
    SEGUR_BLOQUEOS_BLOQUEAR_TARJETAS_Y_CLAVE("link_seguridad_btc"),
    SEGUR_ALERT_NOTIFI_EDITAR_PREFERENCIAS("link_seguridad_alertas"),
    SEGUR_MONT_TRANS_EDITAR_LIMITE_DE_MONTOS("link_seguridad_limiteTransac"),
    SEGUR_CHEQUES_CONTRAORDENAR_CHEQUES("link_seguridad_contraordenCheques"),
    SEGUR_IMAGEN_FRASE_SEGURIDAD_EDITAR("link_seguridad_imageandphrase"),
    DOCU_GENERAR_EXTRACTOS("link_extracts"),
    DOCU_GENERAR_CERTIFICADOS_TRIBUTARIOS("link_certificates"),
    DOCU_GENERAR_REPORTE_ANUAL_DE_COSTOS_TOTALES("link_report"),
    DOCU_GENERAR_PROYECCION_CREDITO_HIPOTECARIO("link_cartas_proyeccion"),
    SOLIC_PRODUC_CRED_SOLICITAR_CREDIAGIL("link_request_rqc"),
    SOLIC_PRODUC_CRED_LIBRE_INVERSION("link_request_fri"),
    SOLIC_PRODUC_CRED_DESEMBOLSAR_CREDIAGIL("link_request_ca"),
    SOLIC_PRODUC_CRED_OTROS_CREDITOS("link_request_roc"),
    SOLIC_PRODUC_INV_FONDO_DE_INVERSION("link_request_fi"),
    SOLIC_PRODUC_INV_INVERSION_VIRTUAL("link_request_iv"),
    SOLIC_PRODUC_TARJETAS_E_PREPAGO("link_request_ep"),
    SOLIC_PRODUC_TARJETAS_E_CARD("link_request_ec"),
    SOLIC_PRODUC_TARJETAS_OTRAS_TARJETAS("link_request_oc"),
    SOLIC_PRODUC_SEGUROS_EXEQUIAL("link_request_ex"),
    SOLIC_PRODUC_SEGUROS_COBERTURA_INTEGRAL("link_request_ic"),
    SOLIC_PRODUC_SEGUROS_PLAN_VIDA_TOTAL("link_request_tlp"),
    PFM_SMART_LINK("link_prod_pfm"),
    SOLIC_PRODUC_SEGUROS_SOAT("link_request_soat"),
    SECURY_BLOCK_BLOQUEO_TEMPORAL("link_seguridad_blocktmptc"),
    DOC_GENE_CERTIFICADO_TRIBUITARIO("link_certificates");

    private String ide;

    TituloSubMenu(String ide) {
        this.ide = ide;
    }

    public String geId() {
        return ide;
    }
}
